package com.uqac.controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import com.uqac.App;

import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.MenuItem;
import javafx.stage.Stage;

public class AccueilAdminController {
	String view;
	String titre;
	@FXML
	private MenuItem listerUser;
	@FXML
	private MenuItem listerImmobilier;
	@FXML
	private MenuItem logout;

	// Event Listener on MenuItem[#listerUser].onAction
		@FXML
		public void listerUser(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="UserListe";
			titre="USER-LISTE";
			app.changeView(view, titre);
		}
		// Event Listener on MenuItem[#listerImmobilier].onAction
		@FXML
		public void listerImmobilier(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="ImmobilierListe";
			titre="IMMOBILIER-LISTE";
			app.changeView(view, titre);
		}
		// Event Listener on MenuItem[#logout].onAction
		@FXML
		public void logout(ActionEvent event) {
			App app = new App();
			view="Login";
			titre="LOGIN";
			app.changeView(view, titre);
		}
}
