package com.uqac.controllers;

import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;

//import java.io.IOException;

import com.uqac.App;

import javafx.event.ActionEvent;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
import javafx.scene.control.MenuItem;
//import javafx.stage.Stage;

public class AccueilAgentController {
	String view;
	String titre;
	@FXML
	private MenuItem Virement;
	@FXML
	private MenuItem Versement;
	@FXML
	private MenuItem Retrait;
	@FXML
	private MenuItem GestionClients;
	@FXML
	private MenuItem GestionComptes;
	@FXML
	private MenuItem logout;

	
	@FXML
	public void GestionClients(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionClient";
		titre="GESTION CLIENT";
		app.changeView(view, titre);
	}
		@FXML
		public void Virement(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Virement";
			titre="VIREMENT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void Versement(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Versement";
			titre="VERSEMENT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void Retrait(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Retrait";
			titre="RETRAIT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void GestionComptes(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Compte";
			titre="Gestion Compte";
			app.changeView(view, titre);
		}
		@FXML
		public void logout(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Login";
			titre="LOGIN";
			app.changeView(view, titre);
		}
}
