package com.uqac.controllers;

import java.time.LocalDate;

import com.uqac.App;
import com.uqac.dao.ClientDao;
//import com.uqac.dao.UserDao;
import com.uqac.entities.Client;
//import com.uqac.entities.User;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.MenuItem;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;

public class ClientController {
	private String view;
	private String titre;
	private static ClientDao dao = new ClientDao();
	@FXML
	private MenuItem GestionClient;
	@FXML
	private MenuItem logout;
	@FXML
	private TextField Nom;
	@FXML
	private PasswordField Prenom;
	@FXML
	private DatePicker DateNaissance;
	@FXML
	private TextField Adresse;
	@FXML
	private TextField NumeroTelephone;
	@FXML
	private Button EnregistrerInfo;


	@FXML
	public void GestionAgent(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionAgent";
		titre="GESTION AGENT";
		app.changeView(view, titre);
	}
	
	@FXML
	public void logout(ActionEvent event) {
		App app = new App();
		view="Login";
		titre="LOGIN";
		app.changeView(view, titre);
	}
	
	@FXML
	
	public void EnregistrerInfo (ActionEvent event) {
		
		Client client = recupererChamp();
		dao.create(client);
		viderChamp();
	}
	
	private Client recupererChamp() {
		Client client = new Client();

		client.setNom(Nom.getText());
		client.setPrenom(Prenom.getText());
		client.setDate_naiss(java.sql.Date.valueOf(DateNaissance.getValue()));
		client.setAdresse(Adresse.getText());
		client.setTelephone(NumeroTelephone.getText());
		
		return client;
	}
	
	private void viderChamp() {
		Nom.textProperty().set("");
		Prenom.textProperty().set("");
		DateNaissance.setValue(LocalDate.now());
		Adresse.textProperty().set("");
		NumeroTelephone.textProperty().set("");
		
	}

}
