package com.uqac.controllers;

import java.awt.TextField;

import com.uqac.App;
import com.uqac.dao.CompteDao;
//import com.uqac.dao.UserDao;
//import com.uqac.entities.User;
import com.uqac.metier.BanqueService;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.MenuItem;

public class RetraitController {
	String view;
	String titre;
	@FXML
	private TextField NumeroCompte;
	@FXML
	private TextField Montant;
	@FXML
	private Button EffectuerRetrait;
	@FXML
	private MenuItem Virement;
	@FXML
	private MenuItem Versement;
	@FXML
	private MenuItem GestionClient;
	@FXML
	private MenuItem GestionCompte;
	@FXML
	private MenuItem logout;

	
	@FXML
	public void GestionClient(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionClient";
		titre="GESTION CLIENT";
		app.changeView(view, titre);
	}
	
	@FXML
	public void Virement(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="Virement";
		titre="VIREMENT";
		app.changeView(view, titre);
	}
		
	@FXML
	public void Versement(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="Versement";
		titre="VERSEMENT";
		app.changeView(view, titre);
	}
		
	@FXML
	public void GestionCompte(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="Compte";
		titre="GESTION COMPTE";
		app.changeView(view, titre);
	}
		
	@FXML
	public void logout(ActionEvent event) {
		App app = new App();
		view="Login";
		titre="LOGIN";
		app.changeView(view, titre);
	}
		
	@FXML
	public void EffectuerRetrait(ActionEvent event) {
			
		long NumC = Long.parseLong(NumeroCompte.getText());
		long Mont = Long.parseLong(Montant.getText());
		CompteDao dao = new CompteDao();
		double Solde = dao.find(NumC).getSolde();
		
		BanqueService Bank = new BanqueService();
		
		if (dao.find(NumC) != null & (Solde>Mont))
		{
			Bank.retrait(NumC,Mont);	 
		}
		else
		{
			Alert info = new Alert(AlertType.ERROR);
		    info.setTitle("Saisie des informations");
		    info.setHeaderText("veuillez saisir des Informations valide");
		    info.showAndWait();
		}
			App app = new App();
			view="AccueilAgent";
			titre="ACCUEIL AGENT";
			app.changeView(view, titre);
		}
		

}
