package com.uqac.controllers;

import java.time.LocalDate;
//import java.util.Date;

import com.uqac.App;
import com.uqac.dao.UserDao;
import com.uqac.entities.User;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
//import javafx.scene.control.ChoiceBox;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.MenuItem;
import javafx.scene.control.PasswordField;
//import javafx.scene.control.TableColumn;
//import javafx.scene.control.TableView;
import javafx.scene.control.TextField;

public class UsersController {

	private String view;
	private String titre;
	private static UserDao dao = new UserDao();
	@FXML
	private MenuItem GestionClient;
	@FXML
	private MenuItem GestionAgent;
	@FXML
	private MenuItem logout;
	@FXML
	private TextField Login;
	@FXML
	private PasswordField Password;
	@FXML
	private DatePicker DateNaissance;
	@FXML
	private TextField Adresse;
	@FXML
	private TextField NumeroTelephone;
	@FXML
	private ComboBox<String>  Role;
	@FXML
	private Button EnregistrerInfo;

	@FXML
	public void initialize() {
	    Role.getItems().removeAll(Role.getItems());
	    Role.getItems().addAll("Admin","Agent");
	    Role.getSelectionModel().select("Admin");
	}

	@FXML
	public void GestionAgent(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionAgent";
		titre="GESTION AGENT";
		app.changeView(view, titre);
	}
	
	@FXML
	public void GestionClient(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionClient";
		titre="GESTION CLIENT";
		app.changeView(view, titre);
	}
	@FXML
	public void logout(ActionEvent event) {
		App app = new App();
		view="Login";
		titre="LOGIN";
		app.changeView(view, titre);
	}
	
	@FXML
	
	public void EnregistrerInfo (ActionEvent event) {
		
		User user = recupererChamp();
		dao.create(user);
		viderChamp();
	}
	
	private User recupererChamp() {
		User user = new User();

		user.setLogin(Login.getText());
		user.setPassword(Password.getText());
		user.setTelephone(NumeroTelephone.getText());
		user.setDate_naiss(java.sql.Date.valueOf(DateNaissance.getValue()));
		user.setAdresse(Adresse.getText());
		user.setRole(Role.getValue().toString());
		return user;
	}
	
	private void viderChamp() {
		Login.textProperty().set("");
		Password.textProperty().set("");
		DateNaissance.setValue(LocalDate.now());
		Adresse.textProperty().set("");
		NumeroTelephone.textProperty().set("");
	}
}
