package com.uqac.controllers;

import java.awt.TextField;

import com.uqac.App;
import com.uqac.dao.CompteDao;
import com.uqac.metier.BanqueService;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.MenuItem;

public class VirementController {
	String view;
	String titre;
	@FXML
	private TextField CompteEmetteur;
	@FXML
	private TextField CompteBeneficiaire;
	@FXML
	private TextField Montant;
	@FXML
	private Button EffectuerVirement;
	@FXML
	private MenuItem Versement;
	@FXML
	private MenuItem retrait;
	@FXML
	private MenuItem GestionClients;
	@FXML
	private MenuItem GestionCompte;
	@FXML
	private MenuItem logout;

	
	@FXML
	public void GestionClients(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionClient";
		titre="GESTION CLIENT";
		app.changeView(view, titre);
	}
		@FXML
		public void Versement(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Versement";
			titre="VERSEMENT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void Retrait(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Retrait";
			titre="RETRAIT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void GestionCompte(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="Compte";
			titre="GESTION COMPTE";
			app.changeView(view, titre);
		}
		
		@FXML
		public void logout(ActionEvent event) {
			App app = new App();
			view="Login";
			titre="LOGIN";
			app.changeView(view, titre);
		}
		
		@FXML
		public void EffectuerVirement(ActionEvent event) {
			
			long NumCE = Long.parseLong(CompteEmetteur.getText());
			long NumCB = Long.parseLong(CompteBeneficiaire.getText());
			long Mont = Long.parseLong(Montant.getText());
			CompteDao dao = new CompteDao();
			double Solde = dao.find(NumCE).getSolde();
			BanqueService Bank = new BanqueService();
			if (dao.find(NumCE) != null & dao.find(NumCB) != null & (Solde>Mont))
			{
				Bank.virement(NumCE, NumCB, Mont);	 
			}
			else
			{
				Alert info = new Alert(AlertType.ERROR);
		           info.setTitle("Saisie des informations");
		           info.setHeaderText("veuillez saisir des Informations valide");
		           info.showAndWait();
			}
			App app = new App();
			view="GestionClients";
			titre="GESTION CLIENTS";
			app.changeView(view, titre);
		}
		

}
